POST {{HostAddress}}/{{AuthAddress}}/refresh/
Accept: application/json
Content-Type: application/json

{
  "id": "3168A16B-4AD4-4204-99FD-212B60B872A6",
  "refreshToken": "PX9px4p/yAQN/xIYyCTNnIOyBCB9AeWusa5/ljT15YE="
}
