POST {{HostAddress}}/{{AuthAddress}}/refresh/
Accept: application/json
Content-Type: application/json

{
  "id": "282d0912-44ba-4e12-8519-ffc3b86f8b74",
  "refreshToken": "6S1PwsbI3/F0VRWQt+ibwhzd7cCpWKtsggpamtd9eEE="
}
