GET {{HostAddress}}/{{TodosAddress}}/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJleHAiOjE3NDc5Mjc2NzEsImVtYWlsIjoicGVkcm9AcCIsImp0aSI6ImEzYTlmYjYyLTA1YWEtNDJlYy05ZjkwLTk3YTY4ZmI3NGUxNyIsInN1YiI6ImVmM2ZmZGQ2LTE1ZGItNDQ3Yy1hNWVmLTllNWEzMjY5NjI5MiIsIm5hbWUiOiJQZWRybyIsImlhdCI6MTc0NzkyNzA3MSwibmJmIjoxNzQ3OTI3MDcxfQ.DdhNuZ4Due6sxhPUsQ3Gu7-r_T1upb6B490eqZnFIJg

###

GET {{HostAddress}}/{{TodosAddress}}/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJleHAiOjE3NDc5MjgxMDQsImVtYWlsIjoicGVkcm9AcCIsImp0aSI6IjE0ZGFkNjg3LWY0YTQtNGNiMC1hMDExLWY5MWNmMDY4Njc2ZSIsInN1YiI6Ijg5MzQ0MjM1LTNmYTEtNGZkNi1iMzRjLTNjM2U2YjA1N2RjMyIsIm5hbWUiOiJQZWRybyIsImlhdCI6MTc0NzkyNzUwNCwibmJmIjoxNzQ3OTI3NTA0fQ.EDD7nNR-8pMeUjbUePS7qKelbGedGKkjyt6VzTxBXfw
