PUT {{HostAddress}}/{{TodosAddress}}/{{TodoId}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "name": "dd",
  "description": "Description",
  "status": 1
}
